"""`python -m secwatch.init` — probe the host and write a draft secwatch.yaml.

Best-effort, non-destructive: prints a review summary, never overwrites an
existing config without --force, and never enables risky features (LLM, etc.)
silently. Review the draft before running secwatch.
"""
import argparse
import sys
from pathlib import Path

import yaml

from . import autodetect

HEADER = """\
# secwatch site config — DRAFT generated by `secwatch init`.
# REVIEW EVERYTHING before use, especially network.trusted_nets (only keep
# hosts/subnets you actually administer from) and endpoint_rules. Copy/rename to
# secwatch.yaml when happy. Any value can also be set via a SECWATCH_* env var.
"""


def main(argv=None):
    ap = argparse.ArgumentParser(prog="secwatch.init",
                                 description="Auto-detect host config → draft secwatch.yaml")
    ap.add_argument("-o", "--output", default="secwatch.draft.yaml",
                    help="where to write the draft (default: secwatch.draft.yaml)")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the draft + summary, write nothing")
    ap.add_argument("--force", action="store_true",
                    help="overwrite the output file if it exists")
    args = ap.parse_args(argv)

    print("secwatch init — probing host…\n", file=sys.stderr)
    draft, notes, meta = autodetect.build_draft()

    print("=== detection summary ===", file=sys.stderr)
    for n in notes:
        print("  •", n, file=sys.stderr)
    print(file=sys.stderr)

    body = HEADER + yaml.safe_dump(draft, sort_keys=False, default_flow_style=False)

    if args.dry_run:
        print(body)
        print("(dry run — nothing written)", file=sys.stderr)
        return 0

    out = Path(args.output)
    if out.exists() and not args.force:
        print(f"refusing to overwrite existing {out} (use --force)", file=sys.stderr)
        return 1
    out.write_text(body)
    print(f"wrote draft → {out}", file=sys.stderr)
    print("Next: review it, then `mv %s secwatch.yaml` and start secwatch."
          % out, file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
