"""`python -m secwatch.install` — first-run setup for a fresh host.

Picks a listen port, creates a local admin account (for the dashboard login),
seeds the config via auto-detection, writes secwatch.yaml, and generates a
systemd unit. Interactive by default; every prompt has a --flag for automation.
Designed for the IP:port crowd — no domain, SSO, or reverse proxy required.
"""
import argparse
import getpass
import os
import socket
import sys
from pathlib import Path

import yaml

from . import auth, autodetect
from .config import BASE_DIR


def _primary_ip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except OSError:
        return "SERVER-IP"


def _ask(prompt, default, provided):
    if provided is not None:
        return provided
    r = input(f"{prompt} [{default}]: ").strip()
    return r or default


def main(argv=None):
    ap = argparse.ArgumentParser(prog="secwatch.install",
                                 description="First-run setup for secwatch")
    ap.add_argument("--host", help="listen address (default 0.0.0.0 for IP:port)")
    ap.add_argument("--port", help="listen port (default 8931)")
    ap.add_argument("--admin-user", help="dashboard admin username")
    ap.add_argument("--admin-password", help="dashboard admin password (else prompt)")
    ap.add_argument("--no-auth", action="store_true",
                    help="skip dashboard auth (only if behind an authenticating proxy)")
    ap.add_argument("--config", default=str(BASE_DIR / "secwatch.yaml"))
    ap.add_argument("--non-interactive", action="store_true")
    ap.add_argument("--force", action="store_true", help="overwrite existing config")
    ap.add_argument("--start", action="store_true",
                    help="install + start the systemd service without prompting")
    ap.add_argument("--no-start", action="store_true",
                    help="just write config + unit, don't install/start the service")
    args = ap.parse_args(argv)
    ni = args.non_interactive

    print("── secwatch first-run setup ──\n", file=sys.stderr)
    cfg_path = Path(args.config)
    if cfg_path.exists() and not args.force:
        print(f"{cfg_path} already exists (use --force to overwrite).", file=sys.stderr)
        return 1

    host = args.host or ("0.0.0.0" if ni else _ask("Listen address", "0.0.0.0", args.host))
    port = args.port or ("8931" if ni else _ask("Listen port", "8931", args.port))

    # auto-detect the rest of the config
    print("\nProbing host for config…", file=sys.stderr)
    draft, notes, _ = autodetect.build_draft()
    for n in notes:
        print("  •", n, file=sys.stderr)

    draft["paths"]["dashboard_url"] = f"http://{_primary_ip()}:{port}/"

    # auth
    generated_pw = None
    if args.no_auth:
        draft["auth"] = {"enabled": False}
        print("\n! dashboard auth DISABLED — only safe behind an authenticating "
              "proxy or on a fully trusted network.", file=sys.stderr)
        user = None
    else:
        user = args.admin_user or ("admin" if ni else _ask("Admin username", "admin",
                                                            args.admin_user))
        pw = args.admin_password
        if not pw:
            if ni:
                import secrets
                pw = secrets.token_urlsafe(12)   # non-interactive → generate one
                generated_pw = pw
            else:
                while True:
                    pw = getpass.getpass("Admin password: ")
                    if pw and pw == getpass.getpass("Confirm password: "):
                        break
                    print("  passwords empty or didn't match, try again", file=sys.stderr)
        draft["auth"] = {"enabled": True, "username": user,
                         "password_hash": auth.hash_password(pw)}

    body = ("# secwatch config — generated by `secwatch install`. Review before use.\n"
            + yaml.safe_dump(draft, sort_keys=False))
    cfg_path.write_text(body)
    try:
        os.chmod(cfg_path, 0o600)  # contains the password hash
    except OSError:
        pass
    print(f"\n✓ wrote {cfg_path}", file=sys.stderr)

    unit = _systemd_unit(host, port)
    unit_path = BASE_DIR / "secwatch.service"
    unit_path.write_text(unit)
    print(f"✓ wrote {unit_path}", file=sys.stderr)

    ip = _primary_ip()
    if args.no_start:
        want = False
    elif args.start or ni:
        want = True
    else:
        want = _ask_yn("\nInstall + start secwatch as a service now?", True)
    creds = ""
    if generated_pw:
        creds = (f"\n   Sign in:   admin / {generated_pw}"
                 f"\n   (auto-generated — SAVE IT; change it in Settings, or re-run with --admin-password)")
    elif user:
        creds = f"\n   Sign in with the admin account you set."
    if want:
        ok, how = _start_service(unit)
        if ok:
            print(f"""
{'='*60}
✅ secwatch is ACTIVE ({how} service — starts on boot, restarts on failure).

   Open  http://{ip}:{port}/{creds}

   Manage it:  systemctl {'--user ' if how == 'user' else ''}status secwatch
{'='*60}
""", file=sys.stderr)
            return 0
        print(f"! couldn't auto-start ({how}) — start it by hand:", file=sys.stderr)

    print(f"""
To run secwatch:
  # foreground:  SECWATCH_HOST={host} SECWATCH_PORT={port} {sys.executable} -m secwatch.main
  # service:     sudo cp {unit_path} /etc/systemd/system/ && sudo systemctl enable --now secwatch
Then open  http://{ip}:{port}/  (review {cfg_path} first).
""", file=sys.stderr)
    return 0


def _ask_yn(prompt, default=True):
    try:
        r = input(f"{prompt} [{'Y/n' if default else 'y/N'}]: ").strip().lower()
    except EOFError:
        return default
    return default if not r else r.startswith("y")


def _start_service(unit_text):
    """Install + enable + start the systemd service. Prefers a system unit (boots
    without login); falls back to a per-user unit. Returns (ok, 'system'|'user'|reason).

    NOTE: privileged commands run WITHOUT capturing output so sudo can prompt for
    a password on the terminal — capturing it hangs/hides the prompt."""
    import shutil
    import subprocess
    import tempfile

    if not shutil.which("systemctl"):
        return False, "no systemd"
    is_root = getattr(os, "geteuid", lambda: 1)() == 0
    sudo = "" if is_root else (shutil.which("sudo") or "")

    if is_root or sudo:
        pfx = [] if is_root else [sudo]
        if sudo:
            print("  (installing the service — enter your sudo password if prompted)",
                  file=sys.stderr)
        tmp = tempfile.NamedTemporaryFile("w", suffix=".service", delete=False)
        tmp.write(unit_text); tmp.close()
        try:
            cp = subprocess.run(pfx + ["cp", tmp.name, "/etc/systemd/system/secwatch.service"])
            if cp.returncode != 0:
                return False, "system"
            subprocess.run(pfx + ["systemctl", "daemon-reload"])
            subprocess.run(pfx + ["systemctl", "enable", "--now", "secwatch"])
        finally:
            os.unlink(tmp.name)
        act = subprocess.run(pfx + ["systemctl", "is-active", "secwatch"],
                             capture_output=True, text=True)
        return act.stdout.strip() == "active", "system"

    # unprivileged: user unit + linger so it survives logout / boots
    d = Path.home() / ".config" / "systemd" / "user"
    d.mkdir(parents=True, exist_ok=True)
    (d / "secwatch.service").write_text(unit_text)
    subprocess.run(["systemctl", "--user", "daemon-reload"])
    subprocess.run(["systemctl", "--user", "enable", "--now", "secwatch"])
    subprocess.run(["loginctl", "enable-linger", os.environ.get("USER", "")],
                   capture_output=True)
    act = subprocess.run(["systemctl", "--user", "is-active", "secwatch"],
                         capture_output=True, text=True)
    return act.stdout.strip() == "active", "user"


def _systemd_unit(host, port):
    return f"""[Unit]
Description=secwatch security monitor
After=network-online.target

[Service]
Type=simple
WorkingDirectory={BASE_DIR}
Environment=PYTHONUNBUFFERED=1
Environment=SECWATCH_HOST={host}
Environment=SECWATCH_PORT={port}
ExecStart={sys.executable} -m secwatch.main
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
"""


if __name__ == "__main__":
    raise SystemExit(main())
