"""`python -m secwatch.install` — first-run setup for a fresh host.

Picks a listen port, creates a local admin account (for the dashboard login),
seeds the config via auto-detection, writes secwatch.yaml, and generates a
systemd unit. Interactive by default; every prompt has a --flag for automation.
Designed for the IP:port crowd — no domain, SSO, or reverse proxy required.
"""
import argparse
import getpass
import os
import socket
import sys
from pathlib import Path

import yaml

from . import auth, autodetect
from .config import BASE_DIR


def _primary_ip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except OSError:
        return "SERVER-IP"


def _ask(prompt, default, provided):
    if provided is not None:
        return provided
    r = input(f"{prompt} [{default}]: ").strip()
    return r or default


def main(argv=None):
    ap = argparse.ArgumentParser(prog="secwatch.install",
                                 description="First-run setup for secwatch")
    ap.add_argument("--host", help="listen address (default 0.0.0.0 for IP:port)")
    ap.add_argument("--port", help="listen port (default 8931)")
    ap.add_argument("--admin-user", help="dashboard admin username")
    ap.add_argument("--admin-password", help="dashboard admin password (else prompt)")
    ap.add_argument("--no-auth", action="store_true",
                    help="skip dashboard auth (only if behind an authenticating proxy)")
    ap.add_argument("--config", default=str(BASE_DIR / "secwatch.yaml"))
    ap.add_argument("--non-interactive", action="store_true")
    ap.add_argument("--force", action="store_true", help="overwrite existing config")
    args = ap.parse_args(argv)
    ni = args.non_interactive

    print("── secwatch first-run setup ──\n", file=sys.stderr)
    cfg_path = Path(args.config)
    if cfg_path.exists() and not args.force:
        print(f"{cfg_path} already exists (use --force to overwrite).", file=sys.stderr)
        return 1

    host = args.host or ("0.0.0.0" if ni else _ask("Listen address", "0.0.0.0", args.host))
    port = args.port or ("8931" if ni else _ask("Listen port", "8931", args.port))

    # auto-detect the rest of the config
    print("\nProbing host for config…", file=sys.stderr)
    draft, notes, _ = autodetect.build_draft()
    for n in notes:
        print("  •", n, file=sys.stderr)

    draft["paths"]["dashboard_url"] = f"http://{_primary_ip()}:{port}/"

    # auth
    if args.no_auth:
        draft["auth"] = {"enabled": False}
        print("\n! dashboard auth DISABLED — only safe behind an authenticating "
              "proxy or on a fully trusted network.", file=sys.stderr)
    else:
        user = args.admin_user or ("admin" if ni else _ask("Admin username", "admin",
                                                            args.admin_user))
        pw = args.admin_password
        if not pw:
            if ni:
                print("--admin-password required with --non-interactive", file=sys.stderr)
                return 1
            while True:
                pw = getpass.getpass("Admin password: ")
                if pw and pw == getpass.getpass("Confirm password: "):
                    break
                print("  passwords empty or didn't match, try again", file=sys.stderr)
        draft["auth"] = {"enabled": True, "username": user,
                         "password_hash": auth.hash_password(pw)}

    body = ("# secwatch config — generated by `secwatch install`. Review before use.\n"
            + yaml.safe_dump(draft, sort_keys=False))
    cfg_path.write_text(body)
    try:
        os.chmod(cfg_path, 0o600)  # contains the password hash
    except OSError:
        pass
    print(f"\n✓ wrote {cfg_path}", file=sys.stderr)

    unit = _systemd_unit(host, port)
    unit_path = BASE_DIR / "secwatch.service"
    unit_path.write_text(unit)
    print(f"✓ wrote {unit_path}", file=sys.stderr)

    ip = _primary_ip()
    print(f"""
Done. To run secwatch:

  # foreground:
  SECWATCH_HOST={host} SECWATCH_PORT={port} {sys.executable} -m secwatch.main

  # or as a service:
  cp {unit_path} ~/.config/systemd/user/    # (or /etc/systemd/system for system-wide)
  systemctl --user daemon-reload && systemctl --user enable --now secwatch

Then open  http://{ip}:{port}/  and sign in.
Review {cfg_path} first — especially network.trusted_nets.
""", file=sys.stderr)
    return 0


def _systemd_unit(host, port):
    return f"""[Unit]
Description=secwatch security monitor
After=network-online.target

[Service]
Type=simple
WorkingDirectory={BASE_DIR}
Environment=PYTHONUNBUFFERED=1
Environment=SECWATCH_HOST={host}
Environment=SECWATCH_PORT={port}
ExecStart={sys.executable} -m secwatch.main
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
"""


if __name__ == "__main__":
    raise SystemExit(main())
